import ollama
import json
import time
import concurrent.futures

class EngineTimeoutError(Exception):
    pass

class EngineValidationError(Exception):
    pass

class OllamaEngine:
    def __init__(self, model_name="llama3"):
        self.model_name = model_name

    def _call_ollama(self, prompt: str) -> str:
        """Internal synchronous call to Ollama."""
        response = ollama.chat(
            model=self.model_name, 
            messages=[{'role': 'user', 'content': prompt}],
            options={'temperature': 0.1} # High determinism
        )
        return response['message']['content']

    def _validate_json(self, raw_output: str) -> dict:
        """Strictly validates the output against the Phase 5 Action Sequence schema."""
        clean_str = raw_output.strip()
        if clean_str.startswith("```json"):
            clean_str = clean_str[7:]
        elif clean_str.startswith("```"):
            clean_str = clean_str[3:]
        if clean_str.endswith("```"):
            clean_str = clean_str[:-3]
        clean_str = clean_str.strip()

        try:
            data = json.loads(clean_str)
        except json.JSONDecodeError as e:
            raise EngineValidationError(f"Invalid JSON format: {e}")

        if "confidence" not in data or "action_sequence" not in data or "response" not in data:
            raise EngineValidationError("Missing required top-level keys ('confidence', 'action_sequence', 'response').")
        
        # Core Type constraints
        if not isinstance(data.get("confidence"), (float, int)):
            raise EngineValidationError("Confidence must be a number.")
        if not isinstance(data.get("response"), str):
            raise EngineValidationError("Response must be a string.")
            
        sequence = data.get("action_sequence")
        if not isinstance(sequence, list):
            raise EngineValidationError("'action_sequence' must be a JSON array.")

        # Validate atomicity items
        for i, item in enumerate(sequence):
            if not isinstance(item, dict):
                raise EngineValidationError(f"Sequence item {i} must be an object.")
                
            action_type = item.get("type")
            if action_type not in ["system", "input"]:
                raise EngineValidationError(f"Sequence item {i} type must be 'system' or 'input'.")
                
            if action_type == "input":
                if "action" not in item or "value" not in item:
                    raise EngineValidationError(f"Input item {i} must contain 'action' and 'value'.")
                if item["action"] not in ["type", "key", "mousemove", "click"]:
                    raise EngineValidationError(f"Input action {i} must be one of: type, key, mousemove, click.")
            elif action_type == "system":
                if "payload" not in item:
                    raise EngineValidationError(f"System item {i} must contain 'payload'.")

        return {
            "confidence": float(data["confidence"]),
            "action_sequence": sequence,
            "response": data["response"]
        }

    def evaluate_intent(self, context_data: dict, enriched_intent: dict, timeout: int = 15, retries: int = 3) -> dict:
        """
        Reasoning layer with Phase 5 Memory Context.
        `enriched_intent` is generated by the new ContextEngine.
        """
        prompt = f"""
You are the central decision layer of Jarvis OS, an AI-native operating system.
You do not use emojis. You do not explain yourself. You only execute intent.

OS State Snapshot:
{json.dumps(context_data, indent=2)}

JARVIS CONTEXT ENGINE (Memory):
{json.dumps(enriched_intent, indent=2)}

User Instruction: "{enriched_intent.get('raw_intent', '')}"

Task: Output a strict JSON string with EXACTLY three keys:
{{
    "confidence": 0.9,
    "action_sequence": [
        {{
            "type": "system",
            "payload": "exact linux bash command string",
            "expected_process": "expected process name (optional)"
        }},
        {{
            "type": "input",
            "action": "type|key|mousemove|click",
            "value": "string or coords",
            "target_window": "focus match (optional)"
        }}
    ],
    "response": "minimal status message"
}}

Rules:
- You must output the entire pipeline as sequential array items.
- If L3_workflow_history matches the intent perfectly, you may confidently mirror that sequence.
- If no action is needed, return an empty array for action_sequence.
"""
        last_error = None
        for attempt in range(retries):
            try:
                with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                    future = executor.submit(self._call_ollama, prompt)
                    raw_output = future.result(timeout=timeout)
                
                validated_data = self._validate_json(raw_output)
                return validated_data

            except concurrent.futures.TimeoutError:
                last_error = EngineTimeoutError(f"AI Engine timed out after {timeout} seconds.")
                print(f"[Engine] WARNING: Timeout on attempt {attempt + 1}/{retries}")
                time.sleep(1)
            except EngineValidationError as e:
                last_error = e
                print(f"[Engine] WARNING: Output validation failed on attempt {attempt + 1}/{retries}: {e}")
                prompt += f"\n[SYSTEM] Previous attempt failed: {str(e)}. MUST return raw valid JSON."
            except Exception as e:
                last_error = Exception(f"AI Engine system failure: {e}")
                print(f"[Engine] ERROR: System failure: {e}")
                time.sleep(1)

        raise last_error
