#!/usr/bin/env python3
"""
JARVIS OS — GRUB Splash Theme Generator
=========================================
Generates the GRUB bootloader theme files (background, fonts, config).
When users power on, they see the Jarvis branding instead of the Linux penguin.

Generates:
  /boot/grub/themes/jarvis/theme.txt
  /boot/grub/themes/jarvis/background.png  (generated via Cairo)
  /boot/grub/themes/jarvis/icons/           (OS selection icons)
"""

import cairo
import math
import os


def generate_grub_background(output_path: str, width=1920, height=1080):
    """
    Renders the GRUB boot screen background using Cairo.
    Dark background with subtle arc reactor in the center.
    """
    surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
    cr = cairo.Context(surface)

    # ── Deep dark gradient background ──
    pat = cairo.LinearGradient(0, 0, 0, height)
    pat.add_color_stop_rgb(0.0, 0.02, 0.02, 0.06)
    pat.add_color_stop_rgb(0.5, 0.03, 0.04, 0.08)
    pat.add_color_stop_rgb(1.0, 0.01, 0.01, 0.04)
    cr.set_source(pat)
    cr.paint()

    cx, cy = width / 2, height / 2 - 30
    blue = (0.20, 0.78, 1.00)

    # ── Subtle radial glow ──
    glow = cairo.RadialGradient(cx, cy, 0, cx, cy, 250)
    glow.add_color_stop_rgba(0.0, blue[0], blue[1], blue[2], 0.06)
    glow.add_color_stop_rgba(0.4, blue[0], blue[1], blue[2], 0.02)
    glow.add_color_stop_rgba(1.0, 0, 0, 0, 0)
    cr.set_source(glow)
    cr.paint()

    # ── Static arc reactor rings ──
    cr.set_line_width(1.5)

    # Outer ring — dashed
    cr.set_source_rgba(blue[0], blue[1], blue[2], 0.15)
    cr.set_dash([20, 15])
    cr.arc(cx, cy, 100, 0, 2 * math.pi)
    cr.stroke()
    cr.set_dash([])

    # Middle ring
    cr.set_source_rgba(blue[0], blue[1], blue[2], 0.25)
    cr.set_line_width(2)
    cr.arc(cx, cy, 60, 0, 2 * math.pi)
    cr.stroke()

    # Inner ring
    cr.set_source_rgba(blue[0], blue[1], blue[2], 0.4)
    cr.arc(cx, cy, 25, 0, 2 * math.pi)
    cr.stroke()

    # Core dot
    cr.set_source_rgba(blue[0], blue[1], blue[2], 0.6)
    cr.arc(cx, cy, 6, 0, 2 * math.pi)
    cr.fill()

    cr.set_source_rgba(1, 1, 1, 0.8)
    cr.arc(cx, cy, 2, 0, 2 * math.pi)
    cr.fill()

    # ── Title ──
    cr.select_font_face("monospace", cairo.FONT_SLANT_NORMAL, cairo.FONT_WEIGHT_BOLD)
    cr.set_font_size(28)
    text = "JARVIS OS"
    extents = cr.text_extents(text)
    cr.set_source_rgba(blue[0], blue[1], blue[2], 0.9)
    cr.move_to(cx - extents.width / 2, cy + 160)
    cr.show_text(text)

    # Subtitle
    cr.set_font_size(12)
    sub = "AI-Native Operating System"
    sub_ext = cr.text_extents(sub)
    cr.set_source_rgba(0.5, 0.55, 0.65, 0.7)
    cr.move_to(cx - sub_ext.width / 2, cy + 185)
    cr.show_text(sub)

    # ── Bottom hint ──
    cr.set_font_size(11)
    hint = "Select an operating system to boot"
    hint_ext = cr.text_extents(hint)
    cr.set_source_rgba(0.4, 0.45, 0.55, 0.6)
    cr.move_to(cx - hint_ext.width / 2, height - 40)
    cr.show_text(hint)

    # Save
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    surface.write_to_png(output_path)
    print(f"[GRUB Theme] Background generated: {output_path}")


def generate_grub_theme_txt(output_path: str):
    """Generates the GRUB theme.txt configuration."""
    theme = """# JARVIS OS GRUB Theme
# Generated by jarvis/ui/grub_theme.py

title-text: ""
desktop-color: "#020206"
desktop-image: "background.png"
terminal-font: "Unifont Regular 16"
terminal-box: "terminal_box_*.png"

+ boot_menu {
    left = 30%
    top = 55%
    width = 40%
    height = 35%
    item_font = "Unifont Regular 16"
    item_color = "#8899aa"
    selected_item_font = "Unifont Regular 16"
    selected_item_color = "#33ccff"
    item_height = 32
    item_spacing = 8
    item_padding = 10
    icon_width = 24
    icon_height = 24
    scrollbar = false
}

+ label {
    left = 30%
    top = 90%
    width = 40%
    align = "center"
    color = "#555566"
    font = "Unifont Regular 12"
    text = "Use arrow keys to select, Enter to boot"
}

+ progress_bar {
    id = "__timeout__"
    left = 35%
    top = 92%
    width = 30%
    height = 4
    fg_color = "#33ccff"
    bg_color = "#1a1a2e"
    border_color = "#33ccff22"
    text_color = "#00000000"
}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(theme)
    print(f"[GRUB Theme] Config generated: {output_path}")


def install_grub_theme(theme_dir="/boot/grub/themes/jarvis"):
    """
    Full theme installation — generates all assets and installs them.
    Must be run as root on the target system.
    """
    os.makedirs(theme_dir, exist_ok=True)

    generate_grub_background(os.path.join(theme_dir, "background.png"))
    generate_grub_theme_txt(os.path.join(theme_dir, "theme.txt"))

    print(f"\n[GRUB Theme] Installed to {theme_dir}")
    print(f"[GRUB Theme] Add to /etc/default/grub:")
    print(f'  GRUB_THEME="{theme_dir}/theme.txt"')
    print(f"  Then run: sudo grub-mkconfig -o /boot/grub/grub.cfg")


if __name__ == "__main__":
    import sys

    if "--install" in sys.argv:
        install_grub_theme()
    else:
        # Just generate preview files locally
        out_dir = os.path.join(os.path.dirname(__file__), "assets")
        os.makedirs(out_dir, exist_ok=True)
        generate_grub_background(os.path.join(out_dir, "grub_background.png"))
        generate_grub_theme_txt(os.path.join(out_dir, "grub_theme.txt"))
        print("\n[Preview] Assets generated in jarvis/ui/assets/")
